### ISSUE TITLE
can not get it to run, not helpful error message: "sxlock: error: could not find font. Try using a full description."

### ISSUE THREAD

**Issue by okurz** [lahwaacz/sxlock#10]
I don't understand how to start it. Maybe the default font can not be found. help would be appreciated.

**Comment by okurz** [comment]
Solved it. It takes X font selections, e.g.

    ./sxlock -f "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*"

Anyway, a sane default would be good or a better usage description might help :-)

**Comment by bbenne10** [comment]
The default is sane. It's "-misc-fixed-medium-r-*--17-120-*-*-*-*-iso8859-1", which should be on most machines that have xorg installed. I'm guessing you have a distro that doesn't package the fonts with the xorg package and didn't/don't have them installed. (Arch comes to mind. They have `xorg-fonts-100dpi` and `xorg-fonts-75dpi`, one of which includes `fixed`, iirc. These packages are recommends, but not required.)

Maybe a better error message would be helpful, but the one that's there seems decent enough to me.

**Comment by okurz** [comment]
thanks for the fast answer.

I am running "openSUSE Leap 42.1 (x86_64)" and just starting up sxlock gives me this message, i.e. it can not find the font. I am wondering how I could list installed X fonts or what I could install to supply the default.

**Comment by bbenne10** [comment]
That's really interesting. I fully expected that you'd be using Arch (which is why I mentioned it). 

To list the fonts available to sxlock, you can issue `xlsfonts`. I'm not 100% sure what package openSuse uses, but could it be `xorg-x11-fonts`?

**Comment by okurz** [comment]
Yes, `xorg-x11-fonts` is installed.

In case you are still interested, output from `xlsfonts`: https://gist.github.com/okurz/d34acdad775c34d97174
