### ISSUE TITLE
Password prompt does not appear when used with xautolock

### ISSUE THREAD

**Issue by Winstr0m** [lahwaacz/sxlock#14]
I use xautolock to start sxlock after 10 minutes of inactivity. When I use the mouse or keyboard to wake the screen up after 10 minutes has passed, everything looks as I left it. I see my desktop and windows, but everything is frozen until I put in the password. No password prompt ever appears.

I use a systemd service to run `xautolock -locknow` when the system wakes up from sleep. When that happens, the screen is black and a password prompt **does** appear.

**Comment by lahwaacz** [comment]
I don't use xautolock, so I will probably not be able to help much. Could you try if other [screen lockers](https://wiki.archlinux.org/index.php/List_of_applications#Screen_lockers) (namely slock and sflock) work or behave the same?

**Comment by Winstr0m** [comment]
I tried using using slock and sflock with xautolock and had no issues. slock shows a black screen and sflock shows a password prompt--both as expected.

**Comment by Winstr0m** [comment]
Apparently this isn't an issue with sxlock after all. While it didn't happen with slock or sflock, it did with i3lock. Setting `IdleAction=ignore` and instead using `xset s 300` to initiate the locker after a period of inactivity fixed it.
