### ISSUE TITLE
-f parameter explanation

### ISSUE THREAD

**Issue by a-kramer** [lahwaacz/sxlock#16]
Hi,
maybe you could write a bit more about the `-f` parameter and possible values. 
This `sxlock -f "Droid Sans Mono"` did not work for me, it returns `sxlock: error: could not find font. Try using a full description.` 
But, it is installed:
```bash
fc-list | grep "Droid Sans Mono"
/usr/share/fonts/TTF/DroidSansMono.ttf: Droid Sans Mono:style=Regular
```

**Comment by lahwaacz** [comment]
See the [default value](https://github.com/lahwaacz/sxlock/blob/master/sxlock.c#L317) and [X logical font description](https://en.wikipedia.org/wiki/X_logical_font_description).

**Comment by a-kramer** [comment]
Thank you very much for the very quick response. May I suggest a change for the manual:
`-f <font description>: modify the font.`
to
`-f <X-logical-font-description>: modify the font (names as in xfontsel).`
