### ISSUE TITLE
Pass through some keys

### ISSUE THREAD

**Issue by blueyed** [lahwaacz/sxlock#17]
Would it be possible to pass through some keys, e.g. to control the audio (mute, lower and raise)?

**Comment by lahwaacz** [comment]
I don't think so, at least not without ditching [XGrabKeyboard](https://github.com/lahwaacz/sxlock/blob/master/sxlock.c#L438) and manually deciding for every key whether to pass it through or not, which I won't do. The point of a screen locker is to lock the desktop, so if you need to punch through the locker, you might as well not use it.
