### ISSUE TITLE
sxlock is circumventable

### ISSUE THREAD

**Issue by limitedAtonement** [lahwaacz/sxlock#27]
I created #23 a couple years ago about my kids crashing sxlock. The child is now seven years old and has figured out how to circumvent sxlock.

After my dell precision m4700 is restored from suspend, the child rails on the keyboard. Right when the desktop comes up (there seems to be a 700ms-or-so pause before sxlock is put on top of the desktop), his typing goes to whatever application was up when the machine was suspended. This prevents sxlock and hinders it from coming to the front to lock the screen.

I can simply not suspend the machines before locking them, but how long will it take before my child will realize he can unplug the power supply until the power gets low and the machine will put itself in suspend?

**Comment by lahwaacz** [comment]
You need to ensure that the screen locker starts before suspend - see e.g. https://github.com/lahwaacz/sxlock#hooking-into-systemd-events
