### ISSUE TITLE
support for background image

### ISSUE THREAD

**Issue by x70b1** [lahwaacz/sxlock#28]
I love the simplicity of `sxlock`.

I would like to be able to set a background image. This would allow more customization.

Unfortunately I am not able to write C. 
So I can only offer this feature request.

**Comment by lahwaacz** [comment]
Adding a background image or any kind of graphics would kill the remaining simplicity. There are plenty of other sufficiently simple screen lockers which support images.

**Comment by x70b1** [comment]
I was expecting this answer. Thanks anyway!
