### ISSUE TITLE
FPrint PAM module doesn't work

### ISSUE THREAD

**Issue by bcspragu** [lahwaacz/sxlock#8]
Adding `auth sufficient pam_fprintd.so` to the sxlock pam file doesn't allow me to use my fingerprint scanner to unlock my computer, while `sudo` and login do.

**Comment by dzizi** [comment]
It does work if you hit enter first, then the light on my fingerprint reader lights up and i can login. At least in my case.

**Comment by bcspragu** [comment]
This worked for me, though my X60 doesn't have a fingerprint reader light. Thanks!
