### ISSUE TITLE
Locking fails with "unclutter -grab"

### ISSUE THREAD

**Issue by rathsky** [lahwaacz/sxlock#9]
If unclutter is run with the -grab option, then sxlock will fail with

> sxlock: Cannot grab pointer/keyboard

when the cursor is hidden.

I'm not sure if this is a bug, but apparently it was relevant enough for slock to include the -nomousegrab option.

**Comment by lahwaacz** [comment]
You might be interested in [unclutter-xfixes](https://github.com/Airblader/unclutter-xfixes) which does not use pointer grabbing.
